# Generated by Django 4.1.4 on 2023-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_streamvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamvideo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='streamvideo',
            name='title',
        ),
        migrations.AlterField(
            model_name='streamvideo',
            name='video_file',
            field=models.FileField(upload_to='streamvideos/'),
        ),
    ]
